/** @type {import('tailwindcss').Config} */
module.exports = {
  // The selector strategy replaced the class strategy in Tailwind CSS v3.4.1.
  darkMode: "selector",
  content: ["./**/*.html"],
  safelist: [
    "select2-container--tailwindcss-3",
    "select2-container--open",
    "select2-container--focus",
    "select2-container--disabled",
    "select2-dropdown",
    "select2-dropdown--below",
    "select2-dropdown--above",
    "select2-selection",
    "select2-selection--single",
    "select2-selection--multiple",
    "select2-selection--clearable",
    "select2-selection__rendered",
    "select2-selection__placeholder",
    "select2-selection__arrow",
    "select2-selection__clear",
    "select2-selection__choice",
    "select2-selection__choice__remove",
    "select2-search",
    "select2-search--dropdown",
    "select2-search--inline",
    "select2-search__field",
    "select2-results",
    "select2-results__options",
    "select2-results__option",
    "select2-results__option--disabled",
    "select2-results__option--highlighted",
    "select2-results__option--selected",
    "select2-results__option--group",
    "select2-results__group",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
